// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/badactor.proto

package badactor

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v3/api"
	client "github.com/micro/go-micro/v3/client"
	server "github.com/micro/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Badactor service

func NewBadactorEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Badactor service

type BadactorService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Badactor_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Badactor_PingPongService, error)
}

type badactorService struct {
	c    client.Client
	name string
}

func NewBadactorService(name string, c client.Client) BadactorService {
	return &badactorService{
		c:    c,
		name: name,
	}
}

func (c *badactorService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Badactor.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *badactorService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Badactor_StreamService, error) {
	req := c.c.NewRequest(c.name, "Badactor.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &badactorServiceStream{stream}, nil
}

type Badactor_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type badactorServiceStream struct {
	stream client.Stream
}

func (x *badactorServiceStream) Close() error {
	return x.stream.Close()
}

func (x *badactorServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *badactorServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *badactorServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *badactorServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *badactorService) PingPong(ctx context.Context, opts ...client.CallOption) (Badactor_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Badactor.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &badactorServicePingPong{stream}, nil
}

type Badactor_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type badactorServicePingPong struct {
	stream client.Stream
}

func (x *badactorServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *badactorServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *badactorServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *badactorServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *badactorServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *badactorServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Badactor service

type BadactorHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Badactor_StreamStream) error
	PingPong(context.Context, Badactor_PingPongStream) error
}

func RegisterBadactorHandler(s server.Server, hdlr BadactorHandler, opts ...server.HandlerOption) error {
	type badactor interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Badactor struct {
		badactor
	}
	h := &badactorHandler{hdlr}
	return s.Handle(s.NewHandler(&Badactor{h}, opts...))
}

type badactorHandler struct {
	BadactorHandler
}

func (h *badactorHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.BadactorHandler.Call(ctx, in, out)
}

func (h *badactorHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.BadactorHandler.Stream(ctx, m, &badactorStreamStream{stream})
}

type Badactor_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type badactorStreamStream struct {
	stream server.Stream
}

func (x *badactorStreamStream) Close() error {
	return x.stream.Close()
}

func (x *badactorStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *badactorStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *badactorStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *badactorStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *badactorHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.BadactorHandler.PingPong(ctx, &badactorPingPongStream{stream})
}

type Badactor_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type badactorPingPongStream struct {
	stream server.Stream
}

func (x *badactorPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *badactorPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *badactorPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *badactorPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *badactorPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *badactorPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
